.TH _printf "1" "15 March 2022" "_printf man page"
.SH NAME
.B _printf
.RS
Output format.
.RE

.SH SYNOPSIS
This function is a Holberton School proyect in which we create are own function.

.SH DESCRIPTION
Function for printing numbers and other thing store in variables acording to the format.


.SH OPTIONS

.B %c
.RS
It prints a single character
.RE

.B %s
.RH
It prints a string
.RE

.B %%
.RH
Identifie the format specification
.RE

.B %i
.RS
It prints a integer. The int argument is converted to signed decimal notation
.RE

.B %d
.RS
It prints a decimal (int). The int argument is converted to signed decimal notation
.RE

.SH SEE ALSO
man (3)printf

.SH BUGS
No known bugs.

.SH AUTHOR
.RI Jose Fabre & Yamil Avila (Chess Crew)

